    create table member
    (
        email varchar(255),
        password varchar(255),
        name varchar(255),
        nickname varchar(255),
        locationX Float,
        locationY Float,
        primary key(email)
    );

    create table board
    (
    id bigint generated by default as identity,
    price bigint,
    title varchar(255),
    text varchar(255),
    category_Id int,
    nickname varchar(255),
    locationX float,
    locationY float,
    register_Date varchar(255),
    deadline_Date varchar(255),
    dibs_Cnt int,
    view_Cnt int,
    chat_Cnt int,
    picture varchar(255),
    primary key(id)
    );

    create table chatMessage
    (
    message_id int by default as identity,
    message varchar(255),
    time timestamp,
    user_id int,
    room_id int,
    primary key(message_id)
    );

    create table chatRoom
    (
    room_id int by default as identity,
    user_id1 int,
    user_id2 int,
    primary key(room_id)
    );
